builds:
  - id: bulkai
    binary: bulkai
    main: ./cmd/bulkai
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: bulkai
    builds:
      - bulkai
    format: zip
    name_template: 'bulkai_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
signs:
- cmd: cosign
  stdin: '{{ .Env.COSIGN_PWD }}'
  args:
  - "sign-blob"
  - "--key=cosign.key"
  - "--output-signature=${signature}"
  - "${artifact}"
  - "--yes" # needed on cosign 2.0.0+
  artifacts: all
