builds:
  - id: bulkai
    binary: bulkai
    main: ./cmd/bulkai
    goarch:
      - amd64
      - arm64
      - arm
  - id: bulkaigui
    binary: bulkaigui
    main: ./cmd/bulkaigui
    goos:
      - darwin
      # TODO: fix building bulkaigui for linux
      # see https://github.com/igolaizola/bulkai/actions/runs/4286376336/jobs/7465884873
      # - linux
    goarch:
      - amd64
      # See https://github.com/igolaizola/bulkai/actions/runs/4297235927/jobs/7489952439
      # - arm64
  - id: bulkaigui-win
    binary: bulkaigui
    main: ./cmd/bulkaigui
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -H=windowsgui
archives:
  - id: bulkai
    builds:
      - bulkai
    format: zip
    name_template: 'bulkai_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
  - id: bulkaigui
    builds:
      - bulkaigui
      - bulkaigui-win
    format: zip
    name_template: 'bulkaigui_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
