name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - name: Libraries for gio
        run: |
          sudo apt update
          sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0' # optional
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
  release-gui-macos:
    needs: goreleaser
    runs-on: macos-12
    environment: main
    steps:
      - id: get-tag
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - name: Build for macos arm64
        run: CGO_ENABLED=1 GOOS="darwin" GOARCH="arm64" go build -ldflags="-s -w -X main.Version=${VERSION}" -o bulkaigui ./cmd/bulkaigui/main.go
        env:
          VERSION: ${{ steps.get-tag.outputs.VERSION }}
      - name: Zip arm64
        run: | 
          zip -r bulkaigui_macos_arm64.zip bulkaigui README.md LICENSE
          rm bulkaigui
      - name: Build for macos - amd64
        run: CGO_ENABLED=1 GOOS="darwin" GOARCH="amd64" go build -ldflags="-s -w -X main.Version=${VERSION}" -o bulkaigui ./cmd/bulkaigui/main.go
        env:
          VERSION: ${{ steps.get-tag.outputs.VERSION }}
      - name: Zip - amd64
        run: |
          zip -r bulkaigui_macos_amd64.zip bulkaigui README.md LICENSE
          rm bulkaigui
      # TODO: add cosign signature
      - name: Upload to the release - arm64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bulkaigui_macos_arm64.zip
          asset_name: "bulkaigui_${{steps.get-tag.outputs.VERSION}}_macos_arm64.zip"
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload to the release - amd64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bulkaigui_macos_amd64.zip
          asset_name: "bulkaigui_${{steps.get-tag.outputs.VERSION}}_macos_amd64.zip"
          tag: ${{ github.ref }}
          overwrite: true